### ISSUE TITLE
Implement y axis or allow for coord_flip

### ISSUE THREAD

**Issue by matiasandina** [schliebs/ggoxford#1]
Hello,
Nice package, I was wondering if you have any plans to add `y` axis functionality or allow for `coord_flip()`. None of these are working right now.

**Comment by schliebs** [comment]
Thank you for reaching out! I don't see a reason why this shouldn't be possible. I might have a look at it next week.

**Comment by schliebs** [comment]
A beta version of this functionality should now be implemented. Please refer to the readme to see an example and do let me know if there is another functionality you'd appreciate to use in the future.

Also, I'm considering upgrading the package from a mostly Oxford-specific package to a general/generic uni/company-branding ggplot-extension, but this will likely only mean a name change and no impact on the flag icon functionality.
